// Routine registration is forwarded from C into Rust so that the linker does
// not discard the static library as unreachable. Without this indirection the
// symbols generated by extendr_module! never make it into the shared object.

void R_init_icebergr_extendr(void *dll);

void R_init_icebergr(void *dll) {
    R_init_icebergr_extendr(dll);
}
