# Generated by extendr: Do not edit by hand
#
# This file would normally be created by rextendr::document(). It declares one R
# function per `#[extendr]` function, calling the `wrap__`-prefixed symbol that
# extendr registers.
#
# `@useDynLib` lives on the package documentation in R/icebergr-package.R rather
# than here: roxygen2 deprecated the `@docType package` block that extendr's
# template puts in this file, and two blocks both claiming to document the
# package collide.

rs_build_info <- function() .Call(wrap__rs_build_info)

rs_ptr_is_null <- function(x) .Call(wrap__rs_ptr_is_null, x)

rs_install_panic_hook <- function() .Call(wrap__rs_install_panic_hook)

rs_catalog_connect <- function(kind, name, storage, keys, values) {
  .Call(wrap__rs_catalog_connect, kind, name, storage, keys, values)
}

rs_list_namespaces <- function(cat, parent) .Call(wrap__rs_list_namespaces, cat, parent)

rs_list_tables <- function(cat, namespace) .Call(wrap__rs_list_tables, cat, namespace)

rs_namespace_exists <- function(cat, namespace) {
  .Call(wrap__rs_namespace_exists, cat, namespace)
}

rs_create_namespace <- function(cat, namespace) {
  .Call(wrap__rs_create_namespace, cat, namespace)
}

rs_table_open <- function(cat, namespace, name) {
  .Call(wrap__rs_table_open, cat, namespace, name)
}

rs_table_exists <- function(cat, namespace, name) {
  .Call(wrap__rs_table_exists, cat, namespace, name)
}

rs_table_reload <- function(tbl) .Call(wrap__rs_table_reload, tbl)

rs_create_table <- function(cat, namespace, name, schema_addr, location) {
  .Call(wrap__rs_create_table, cat, namespace, name, schema_addr, location)
}

rs_register_table <- function(cat, namespace, name, metadata_location) {
  .Call(wrap__rs_register_table, cat, namespace, name, metadata_location)
}

rs_table_identifier <- function(tbl) .Call(wrap__rs_table_identifier, tbl)

rs_table_location <- function(tbl) .Call(wrap__rs_table_location, tbl)

rs_table_format_version <- function(tbl) .Call(wrap__rs_table_format_version, tbl)

rs_table_schema <- function(tbl, snapshot_id) {
  .Call(wrap__rs_table_schema, tbl, snapshot_id)
}

rs_table_partitions <- function(tbl) .Call(wrap__rs_table_partitions, tbl)

rs_table_snapshots <- function(tbl) .Call(wrap__rs_table_snapshots, tbl)

rs_table_history <- function(tbl) .Call(wrap__rs_table_history, tbl)

rs_table_current_snapshot <- function(tbl) .Call(wrap__rs_table_current_snapshot, tbl)

rs_table_properties <- function(tbl) .Call(wrap__rs_table_properties, tbl)

rs_scan_to_stream <- function(tbl, select, filter_json, snapshot_id, batch_size,
                              case_sensitive, row_group_filtering, row_selection,
                              stream_addr) {
  .Call(
    wrap__rs_scan_to_stream, tbl, select, filter_json, snapshot_id, batch_size,
    case_sensitive, row_group_filtering, row_selection, stream_addr
  )
}

rs_scan_plan <- function(tbl, select, filter_json, snapshot_id, case_sensitive) {
  .Call(wrap__rs_scan_plan, tbl, select, filter_json, snapshot_id, case_sensitive)
}

rs_table_append <- function(tbl, stream_addr, compression, property_keys,
                            property_values) {
  .Call(
    wrap__rs_table_append, tbl, stream_addr, compression, property_keys,
    property_values
  )
}
